export const APP_PATH = {
  HOME: '/',
  DESIGN: '/design',
  INTRO: '/intro',
  KAKAO_OAUTH: '/oauth/kakao',
  LOGIN: '/login',
  SIGNUP: '/signup',
  ACCOUNT_FIND: '/account-find',
  TERMS: '/terms',
  EVENTS: '/events',
  EVENT_SEARCH: '/events/search',
  EVENT_NEW: '/events/new',
  MY: '/my',
  MY_EVENTS: '/my/events',
  MY_EDIT: '/my/edit',
  ACCOUNT_DELETE: '/account-delete',
} as const;
