type ColorValue = string;

export type ColorMode = 'light' | 'dark';

// Primitive color values can change when Figma tokens are updated. Prefer semantic color tokens in product components.
export const colorPrimitive = {
  neutral: {
    '0': '#FFFFFF',
    '50': '#F7F9FB',
    '100': '#EEF2F6',
    '200': '#E0E6EC',
    '300': '#C9D2DC',
    '400': '#AEBBC9',
    '500': '#7D8A9A',
    '600': '#5D6876',
    '700': '#454F5C',
    '800': '#2F3947',
    '850': '#202933',
    '900': '#151B23',
    '950': '#0E1319',
    '950-a54': 'rgba(18, 24, 32, 0.54)',
    '800-a10': 'rgba(51, 59, 70, 0.1)',
    '300-a24': 'rgba(201, 210, 220, 0.24)',
    '0-a8': 'rgba(255, 255, 255, 0.08)',
    '50-a32': 'rgba(247, 249, 251, 0.32)',
    '0-a16': 'rgba(255, 255, 255, 0.16)',
    '0-a32': 'rgba(255, 255, 255, 0.32)',
    '950-a42': 'rgba(18, 24, 32, 0.42)',
    '950-a18': 'rgba(18, 24, 32, 0.18)',
  },
  red: {
    '50': '#FEF3F2',
    '400': '#FF6B61',
    '500': '#F04438',
  },
  brand: {
    cyan: {
      '50': '#EBFDFF',
      '100': '#C5EEFA',
      '200': '#91DCF4',
      '300': '#5ECCF0',
      '400': '#2BAFE0',
      '500': '#009BDB',
      '600': '#0087C0',
      '700': '#026F99',
      '800': '#0C5B7D',
      '900': '#134263',
      '950': '#06314F',
      '500-a10': 'rgba(0, 155, 219, 0.1)',
      '400-a12': 'rgba(43, 175, 224, 0.12)',
      '500-a24': 'rgba(0, 155, 219, 0.24)',
      '400-a20': 'rgba(43, 175, 224, 0.2)',
    },
    mint: {
      'mint-weak': 'rgba(104, 209, 194, 0.16)',
    },
  },
  profile: {
    'team-a': '#C9532E',
    'team-b': '#CE8E38',
    'team-c': '#6C9D34',
    'team-d': '#408797',
    'team-e': '#3F6EBC',
    'visual impairment': '#CB4670',
    guide: '#5A5CD1',
  },
} as const;

export const primitiveColorTokenMap = {
  'primitive.neutral.0': '#FFFFFF',
  'primitive.neutral.50': '#F7F9FB',
  'primitive.neutral.100': '#EEF2F6',
  'primitive.neutral.200': '#E0E6EC',
  'primitive.neutral.300': '#C9D2DC',
  'primitive.neutral.400': '#AEBBC9',
  'primitive.neutral.500': '#7D8A9A',
  'primitive.neutral.600': '#5D6876',
  'primitive.neutral.700': '#454F5C',
  'primitive.neutral.800': '#2F3947',
  'primitive.neutral.850': '#202933',
  'primitive.neutral.900': '#151B23',
  'primitive.neutral.950': '#0E1319',
  'primitive.neutral.950-a54': 'rgba(18, 24, 32, 0.54)',
  'primitive.neutral.800-a10': 'rgba(51, 59, 70, 0.1)',
  'primitive.neutral.300-a24': 'rgba(201, 210, 220, 0.24)',
  'primitive.neutral.0-a8': 'rgba(255, 255, 255, 0.08)',
  'primitive.neutral.50-a32': 'rgba(247, 249, 251, 0.32)',
  'primitive.neutral.0-a16': 'rgba(255, 255, 255, 0.16)',
  'primitive.neutral.0-a32': 'rgba(255, 255, 255, 0.32)',
  'primitive.neutral.950-a42': 'rgba(18, 24, 32, 0.42)',
  'primitive.neutral.950-a18': 'rgba(18, 24, 32, 0.18)',
  'primitive.red.50': '#FEF3F2',
  'primitive.red.400': '#FF6B61',
  'primitive.red.500': '#F04438',
  'primitive.brand.cyan.50': '#EBFDFF',
  'primitive.brand.cyan.100': '#C5EEFA',
  'primitive.brand.cyan.200': '#91DCF4',
  'primitive.brand.cyan.300': '#5ECCF0',
  'primitive.brand.cyan.400': '#2BAFE0',
  'primitive.brand.cyan.500': '#009BDB',
  'primitive.brand.cyan.600': '#0087C0',
  'primitive.brand.cyan.700': '#026F99',
  'primitive.brand.cyan.800': '#0C5B7D',
  'primitive.brand.cyan.900': '#134263',
  'primitive.brand.cyan.950': '#06314F',
  'primitive.brand.cyan.500-a10': 'rgba(0, 155, 219, 0.1)',
  'primitive.brand.cyan.400-a12': 'rgba(43, 175, 224, 0.12)',
  'primitive.brand.cyan.500-a24': 'rgba(0, 155, 219, 0.24)',
  'primitive.brand.cyan.400-a20': 'rgba(43, 175, 224, 0.2)',
  'primitive.brand.mint.mint-weak': 'rgba(104, 209, 194, 0.16)',
  'primitive.profile.team-a': '#C9532E',
  'primitive.profile.team-b': '#CE8E38',
  'primitive.profile.team-c': '#6C9D34',
  'primitive.profile.team-d': '#408797',
  'primitive.profile.team-e': '#3F6EBC',
  'primitive.profile.visual impairment': '#CB4670',
  'primitive.profile.guide': '#5A5CD1',
} as const;

export type PrimitiveColorToken = keyof typeof primitiveColorTokenMap;

export const semanticColorAliases = {
  light: {
    bg: {
      default: 'primitive.neutral.0',
      subtle: 'primitive.neutral.50',
      surface: 'primitive.neutral.0',
      elevated: 'primitive.neutral.0',
      brand: 'primitive.brand.cyan.500',
      'brand-soft': 'primitive.brand.cyan.50',
      'dim-strong': 'primitive.neutral.950-a54',
      'light-strong': 'primitive.neutral.50-a32',
      'brand-subtle': 'primitive.brand.cyan.500-a24',
      'light-soft': 'primitive.neutral.0-a8',
      'dim-soft': 'primitive.neutral.950-a42',
      overlay: 'primitive.neutral.950-a18',
      // Compatibility aliases for early app screens that still use the previous token names.
      dim: 'primitive.neutral.950-a54',
      weak: 'primitive.neutral.300-a24',
      'brand-weak': 'primitive.brand.cyan.500-a10',
      'brand-weak2': 'primitive.brand.cyan.500-a24',
      inverse: 'primitive.neutral.800',
    },
    text: {
      primary: 'primitive.neutral.900',
      secondary: 'primitive.neutral.700',
      tertiary: 'primitive.neutral.500',
      quaternary: 'primitive.neutral.400',
      inverse: 'primitive.neutral.0',
      brand: 'primitive.brand.cyan.500',
      disabled: 'primitive.neutral.950-a54',
      danger: 'primitive.red.500',
    },
    border: {
      default: 'primitive.neutral.300',
      subtle: 'primitive.neutral.200',
      danger: 'primitive.red.500',
      focused: 'primitive.brand.cyan.500-a24',
      strong: 'primitive.neutral.950-a18',
      brand: 'primitive.brand.cyan.500',
      primary: 'primitive.neutral.900',
    },
    profile: {
      'team-a': 'primitive.profile.team-a',
      'team-b': 'primitive.profile.team-b',
      'team-c': 'primitive.profile.team-c',
      'team-d': 'primitive.profile.team-d',
      'team-e': 'primitive.profile.team-e',
    },
    icon: {
      primary: 'primitive.neutral.900',
      secondary: 'primitive.neutral.500',
      teritary: 'primitive.neutral.400',
      tertiary: 'primitive.neutral.400',
      inverse: 'primitive.neutral.0',
      brand: 'primitive.brand.cyan.500',
    },
  },
  dark: {
    bg: {
      default: 'primitive.neutral.950',
      subtle: 'primitive.neutral.900',
      surface: 'primitive.neutral.850',
      elevated: 'primitive.neutral.950',
      brand: 'primitive.brand.cyan.400',
      'brand-soft': 'primitive.brand.cyan.400-a12',
      'dim-strong': 'primitive.neutral.950-a54',
      'light-strong': 'primitive.neutral.50-a32',
      'brand-subtle': 'primitive.brand.cyan.400-a20',
      'light-soft': 'primitive.neutral.0-a8',
      'dim-soft': 'primitive.neutral.950-a42',
      overlay: 'primitive.neutral.0-a8',
      dim: 'primitive.neutral.950-a54',
      weak: 'primitive.neutral.50-a32',
      'brand-weak': 'primitive.brand.cyan.400-a12',
      'brand-weak2': 'primitive.brand.cyan.400-a20',
      inverse: 'primitive.neutral.100',
    },
    text: {
      primary: 'primitive.neutral.50',
      secondary: 'primitive.neutral.400',
      tertiary: 'primitive.neutral.500',
      quaternary: 'primitive.neutral.600',
      inverse: 'primitive.neutral.950',
      brand: 'primitive.brand.cyan.400',
      disabled: 'primitive.neutral.950-a54',
      danger: 'primitive.red.400',
    },
    border: {
      default: 'primitive.neutral.0-a16',
      subtle: 'primitive.neutral.0-a8',
      danger: 'primitive.red.400',
      focused: 'primitive.brand.cyan.400-a20',
      strong: 'primitive.neutral.0-a32',
      brand: 'primitive.brand.cyan.400',
      primary: 'primitive.neutral.50',
    },
    profile: {
      'team-a': 'primitive.profile.team-a',
      'team-b': 'primitive.profile.team-b',
      'team-c': 'primitive.profile.team-c',
      'team-d': 'primitive.profile.team-d',
      'team-e': 'primitive.profile.team-e',
    },
    icon: {
      primary: 'primitive.neutral.100',
      secondary: 'primitive.neutral.500',
      teritary: 'primitive.neutral.600',
      tertiary: 'primitive.neutral.600',
      inverse: 'primitive.neutral.850',
      brand: 'primitive.brand.cyan.400',
    },
  },
} as const;

export const semanticColorModes = {
  light: {
    bg: {
      default: '#FFFFFF',
      subtle: '#F7F9FB',
      surface: '#FFFFFF',
      elevated: '#FFFFFF',
      brand: '#009BDB',
      'brand-soft': '#EBFDFF',
      'dim-strong': 'rgba(18, 24, 32, 0.54)',
      'light-strong': 'rgba(247, 249, 251, 0.32)',
      'brand-subtle': 'rgba(0, 155, 219, 0.24)',
      'light-soft': 'rgba(255, 255, 255, 0.08)',
      'dim-soft': 'rgba(18, 24, 32, 0.42)',
      overlay: 'rgba(18, 24, 32, 0.18)',
      dim: 'rgba(18, 24, 32, 0.54)',
      weak: 'rgba(201, 210, 220, 0.24)',
      'brand-weak': 'rgba(0, 155, 219, 0.1)',
      'brand-weak2': 'rgba(0, 155, 219, 0.24)',
      inverse: '#2F3947',
    },
    text: {
      primary: '#151B23',
      secondary: '#454F5C',
      tertiary: '#7D8A9A',
      quaternary: '#AEBBC9',
      inverse: '#FFFFFF',
      brand: '#009BDB',
      disabled: 'rgba(18, 24, 32, 0.54)',
      danger: '#F04438',
    },
    border: {
      default: '#C9D2DC',
      subtle: '#E0E6EC',
      danger: '#F04438',
      focused: 'rgba(0, 155, 219, 0.24)',
      strong: 'rgba(18, 24, 32, 0.18)',
      brand: '#009BDB',
      primary: '#151B23',
    },
    profile: {
      'team-a': '#C9532E',
      'team-b': '#CE8E38',
      'team-c': '#6C9D34',
      'team-d': '#408797',
      'team-e': '#3F6EBC',
    },
    icon: {
      primary: '#151B23',
      secondary: '#7D8A9A',
      teritary: '#AEBBC9',
      tertiary: '#AEBBC9',
      inverse: '#FFFFFF',
      brand: '#009BDB',
    },
  },
  dark: {
    bg: {
      default: '#0E1319',
      subtle: '#151B23',
      surface: '#202933',
      elevated: '#0E1319',
      brand: '#2BAFE0',
      'brand-soft': 'rgba(43, 175, 224, 0.12)',
      'dim-strong': 'rgba(18, 24, 32, 0.54)',
      'light-strong': 'rgba(247, 249, 251, 0.32)',
      'brand-subtle': 'rgba(43, 175, 224, 0.2)',
      'light-soft': 'rgba(255, 255, 255, 0.08)',
      'dim-soft': 'rgba(18, 24, 32, 0.42)',
      overlay: 'rgba(255, 255, 255, 0.08)',
      dim: 'rgba(18, 24, 32, 0.54)',
      weak: 'rgba(247, 249, 251, 0.32)',
      'brand-weak': 'rgba(43, 175, 224, 0.12)',
      'brand-weak2': 'rgba(43, 175, 224, 0.2)',
      inverse: '#EEF2F6',
    },
    text: {
      primary: '#F7F9FB',
      secondary: '#AEBBC9',
      tertiary: '#7D8A9A',
      quaternary: '#5D6876',
      inverse: '#0E1319',
      brand: '#2BAFE0',
      disabled: 'rgba(18, 24, 32, 0.54)',
      danger: '#FF6B61',
    },
    border: {
      default: 'rgba(255, 255, 255, 0.16)',
      subtle: 'rgba(255, 255, 255, 0.08)',
      danger: '#FF6B61',
      focused: 'rgba(43, 175, 224, 0.2)',
      strong: 'rgba(255, 255, 255, 0.32)',
      brand: '#2BAFE0',
      primary: '#F7F9FB',
    },
    profile: {
      'team-a': '#C9532E',
      'team-b': '#CE8E38',
      'team-c': '#6C9D34',
      'team-d': '#408797',
      'team-e': '#3F6EBC',
    },
    icon: {
      primary: '#EEF2F6',
      secondary: '#7D8A9A',
      teritary: '#5D6876',
      tertiary: '#5D6876',
      inverse: '#202933',
      brand: '#2BAFE0',
    },
  },
} as const;

export const color = {
  bg: {
    default: 'var(--color-bg-default)',
    subtle: 'var(--color-bg-subtle)',
    surface: 'var(--color-bg-surface)',
    elevated: 'var(--color-bg-elevated)',
    brand: 'var(--color-bg-brand)',
    'brand-soft': 'var(--color-bg-brand-soft)',
    'dim-strong': 'var(--color-bg-dim-strong)',
    'light-strong': 'var(--color-bg-light-strong)',
    'brand-subtle': 'var(--color-bg-brand-subtle)',
    'light-soft': 'var(--color-bg-light-soft)',
    'dim-soft': 'var(--color-bg-dim-soft)',
    overlay: 'var(--color-bg-overlay)',
    dim: 'var(--color-bg-dim)',
    weak: 'var(--color-bg-weak)',
    'brand-weak': 'var(--color-bg-brand-weak)',
    'brand-weak2': 'var(--color-bg-brand-weak2)',
    inverse: 'var(--color-bg-inverse)',
  },
  text: {
    primary: 'var(--color-text-primary)',
    secondary: 'var(--color-text-secondary)',
    tertiary: 'var(--color-text-tertiary)',
    quaternary: 'var(--color-text-quaternary)',
    inverse: 'var(--color-text-inverse)',
    brand: 'var(--color-text-brand)',
    disabled: 'var(--color-text-disabled)',
    danger: 'var(--color-text-danger)',
  },
  border: {
    default: 'var(--color-border-default)',
    subtle: 'var(--color-border-subtle)',
    danger: 'var(--color-border-danger)',
    focused: 'var(--color-border-focused)',
    strong: 'var(--color-border-strong)',
    brand: 'var(--color-border-brand)',
    primary: 'var(--color-border-primary)',
  },
  profile: {
    'team-a': 'var(--color-profile-team-a)',
    'team-b': 'var(--color-profile-team-b)',
    'team-c': 'var(--color-profile-team-c)',
    'team-d': 'var(--color-profile-team-d)',
    'team-e': 'var(--color-profile-team-e)',
  },
  icon: {
    primary: 'var(--color-icon-primary)',
    secondary: 'var(--color-icon-secondary)',
    teritary: 'var(--color-icon-teritary)',
    tertiary: 'var(--color-icon-tertiary)',
    inverse: 'var(--color-icon-inverse)',
    brand: 'var(--color-icon-brand)',
  },
} as const;

export const colorTokenMap = {
  'bg.default': 'var(--color-bg-default)',
  'bg.subtle': 'var(--color-bg-subtle)',
  'bg.surface': 'var(--color-bg-surface)',
  'bg.elevated': 'var(--color-bg-elevated)',
  'bg.brand': 'var(--color-bg-brand)',
  'bg.brand-soft': 'var(--color-bg-brand-soft)',
  'bg.dim-strong': 'var(--color-bg-dim-strong)',
  'bg.light-strong': 'var(--color-bg-light-strong)',
  'bg.brand-subtle': 'var(--color-bg-brand-subtle)',
  'bg.light-soft': 'var(--color-bg-light-soft)',
  'bg.dim-soft': 'var(--color-bg-dim-soft)',
  'bg.overlay': 'var(--color-bg-overlay)',
  'bg.dim': 'var(--color-bg-dim)',
  'bg.weak': 'var(--color-bg-weak)',
  'bg.brand-weak': 'var(--color-bg-brand-weak)',
  'bg.brand-weak2': 'var(--color-bg-brand-weak2)',
  'bg.inverse': 'var(--color-bg-inverse)',
  'text.primary': 'var(--color-text-primary)',
  'text.secondary': 'var(--color-text-secondary)',
  'text.tertiary': 'var(--color-text-tertiary)',
  'text.quaternary': 'var(--color-text-quaternary)',
  'text.inverse': 'var(--color-text-inverse)',
  'text.brand': 'var(--color-text-brand)',
  'text.disabled': 'var(--color-text-disabled)',
  'text.danger': 'var(--color-text-danger)',
  'border.default': 'var(--color-border-default)',
  'border.subtle': 'var(--color-border-subtle)',
  'border.danger': 'var(--color-border-danger)',
  'border.focused': 'var(--color-border-focused)',
  'border.strong': 'var(--color-border-strong)',
  'border.brand': 'var(--color-border-brand)',
  'border.primary': 'var(--color-border-primary)',
  'profile.team-a': 'var(--color-profile-team-a)',
  'profile.team-b': 'var(--color-profile-team-b)',
  'profile.team-c': 'var(--color-profile-team-c)',
  'profile.team-d': 'var(--color-profile-team-d)',
  'profile.team-e': 'var(--color-profile-team-e)',
  'icon.primary': 'var(--color-icon-primary)',
  'icon.secondary': 'var(--color-icon-secondary)',
  'icon.teritary': 'var(--color-icon-teritary)',
  'icon.tertiary': 'var(--color-icon-tertiary)',
  'icon.inverse': 'var(--color-icon-inverse)',
  'icon.brand': 'var(--color-icon-brand)',
} as const;

export type ColorToken = keyof typeof colorTokenMap;

export const resolveColorToken = (token: ColorToken): ColorValue => colorTokenMap[token];

const flattenSemanticColors = (
  value: Record<string, unknown>,
  path: string[] = [],
): Array<[name: string, color: string]> => {
  return Object.entries(value).flatMap(([key, childValue]) => {
    const nextPath = [...path, key];

    if (typeof childValue === 'string') {
      return [[nextPath.join('-'), childValue] as [string, string]];
    }

    return flattenSemanticColors(childValue as Record<string, unknown>, nextPath);
  });
};

const createColorModeCssVariables = (modeColors: Record<string, unknown>) => {
  return flattenSemanticColors(modeColors)
    .map(([name, value]) => `  --color-${name}: ${value};`)
    .join('\n');
};

export const colorModeCssVariables = {
  light: createColorModeCssVariables(semanticColorModes.light),
  dark: createColorModeCssVariables(semanticColorModes.dark),
} as const satisfies Record<ColorMode, string>;
